spring:
  application:
    name: Library-Management-System
  datasource:
    url: jdbc:mysql://localhost:3306/lib_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
